name: base
<<<<<<< HEAD
=======
channels:
  - defaults
>>>>>>> a573b4d (Commit changes before rebase)
dependencies:
  - python=3.10
  - flask
  - joblib
  - numpy
  - scikit-learn
  - pip
  - pip:
    - pytest
    - flake8
